-- 농장 정보 확장: 대표자명, 사업자번호, 농장종류, 농장주소, 담당자, 사무실/FAX
-- (농장명=farmName 은 기존 컬럼)

ALTER TABLE farms ADD COLUMN IF NOT EXISTS "ownerName" TEXT;
ALTER TABLE farms ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE farms ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE farms ADD COLUMN IF NOT EXISTS "businessNumber" TEXT;
ALTER TABLE farms ADD COLUMN IF NOT EXISTS "farmType" TEXT;
ALTER TABLE farms ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE farms ADD COLUMN IF NOT EXISTS "contactName" TEXT;
ALTER TABLE farms ADD COLUMN IF NOT EXISTS "contactPhone" TEXT;
ALTER TABLE farms ADD COLUMN IF NOT EXISTS "contactEmail" TEXT;
ALTER TABLE farms ADD COLUMN IF NOT EXISTS "officePhone" TEXT;
ALTER TABLE farms ADD COLUMN IF NOT EXISTS "faxNumber" TEXT;
